version: 0.0
os: linux
files:
 - source: /index.html
   destination: /var/www/html
hooks:
 Afterinstall:
 #- location: /scripts/httpd_install.sh
    # runas: root
  - location: /scripts/httpd_start.sh
    
    runas: root
 


